version: ~> 1.0
dist: xenial
language: cpp
compiler: gcc
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - sudo apt-get -y install gcc-7
  - eval "${MATRIX_EVAL}"
addons:
  apt:
    sources:
    - sourceline: 'deb https://packages.chef.io/repos/apt/stable trusty main'
      - ubuntu-toolchain-r-test
    packages:
      - libboost-test-dev
      - g++-7
script:
  - sudo apt-get update
  - cmake .
  - cmake --build .
  #- cmake --build . --target test
  - cmake --build . --target package
  